## ENCODING

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars (1).csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [3]:
df.sample(5)

        brand  km_driven    fuel         owner  selling_price
1046   Maruti      10000  Petrol   First Owner         600000
6415     Tata      25000  Petrol  Second Owner          85000
1985   Maruti      58511  Diesel   First Owner         950000
1159  Hyundai       3000  Diesel   First Owner         700000
7207  Hyundai      60000  Petrol  Second Owner         280000

In [4]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [5]:
df['brand'].value_counts()
df['brand'].nunique()

32

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# 1. ONE HOT ENCODING USING PANDAS

In [7]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# 2. K-1 ONE HOT ENCODING

In [8]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3. ONE HOT ENCODING USING SKLEARN

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [10]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [11]:
x_train.head()

        brand  km_driven    fuel         owner
5918  Hyundai      75000  Petrol  Second Owner
6122     Tata     140000  Diesel   First Owner
4043     Tata      90000  Diesel  Second Owner
1136   Jaguar      45000  Diesel   First Owner
2312   Maruti      80000     CNG  Second Owner

In [12]:
x_test.head()

         brand  km_driven    fuel         owner
1069     Skoda      99000  Diesel   First Owner
999     Maruti      60000  Petrol  Second Owner
1216  Mahindra       5000  Diesel  Second Owner
4139      Ford      70000  Diesel   First Owner
6253   Hyundai      97000     LPG   Third Owner

# IMPORT OHE: SK Learn

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [16]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [17]:
x_test_new = ohe.fit_transform(x_test[['fuel','owner']])

In [18]:
x_train_new

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0]], dtype=int32)

In [20]:
x_train_new.shape

(6502, 7)

In [21]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 75000, 0, ..., 1, 0, 0],
       ['Tata', 140000, 1, ..., 0, 0, 0],
       ['Tata', 90000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 43000, 1, ..., 0, 0, 0],
       ['Hyundai', 60000, 0, ..., 0, 0, 1],
       ['Mahindra', 47990, 1, ..., 1, 0, 0]], dtype=object)