In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('train (5).csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df = pd.read_csv('train (5).csv')[['Age', 'Pclass', 'SibSp', 'Parch', 'Survived']]
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

# Drop NA Value

In [4]:
df.dropna(inplace=True)
df.sample(5)

      Age  Pclass  SibSp  Parch  Survived
800  34.0       2      0      0         0
337  41.0       1      0      0         1
398  23.0       2      0      0         0
576  34.0       2      0      0         1
120  21.0       2      2      0         0

# Separate X ana Y

In [5]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [6]:
x.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [7]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# Check Accuracy for Logistics Regression

In [8]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

# Applying Feature Construction

## Create New Column

In [9]:
x['Family_size'] = x['SibSp'] + x['Parch'] + 1

In [10]:
x.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

# Apply New Function

In [11]:
def myfunc(num):
    if num == 1:
        # alone
        return 0
    elif num > 1 and num <= 4:
        # Small family
        return 1
    else:
        # Large family
        return 2

In [12]:
myfunc(4)

1

# Apply M Function

In [13]:
x['Family_type'] = x['Family_size'].apply(myfunc)
x.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

# Drop Unwanted Columns

In [14]:
x.drop(columns=['SibSp', 'Parch', 'Family_size'],inplace=True)

In [15]:
x.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

# Review Accuracy After Feature Contruction

In [16]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)