## API KEY:

In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ee0613e81f2b8297033ecb3c4d61d421&language=en-US&page=1')

### 6 c=Column select code

In [3]:
df = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity','vote_average']]

In [6]:
df.head()

,id,title,release_date,overview,popularity,vote_average
0,1007757,Swapped,2026-05-01,"A small woodland creature and a majestic bird,...",216.7283,8.970
1,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,67.7713,8.722
2,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",43.1905,8.687
3,687163,Project Hail Mary,2026-03-15,Science teacher Ryland Grace wakes up on a spa...,248.3935,8.655
4,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,28.6290,8.571

### Get a data from page 5

In [17]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ee0613e81f2b8297033ecb3c4d61d421&language=en-US&page=5')

In [18]:
df1 = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity','vote_average']]
df1

,id,title,release_date,overview,popularity,vote_average
0,92321,Hotarubi no Mori e,2011-09-17,One hot summer day a little girl gets lost in ...,0.0101,8.255
1,18491,Neon Genesis Evangelion: The End of Evangelion,1997-07-19,"SEELE orders an all-out attack on NERV, aiming...",10.1749,8.300
2,8587,The Lion King,1994-06-15,"Young lion prince Simba, eager to one day beco...",25.9034,8.254
3,975,Paths of Glory,1957-10-25,A commanding officer defends three scapegoats ...,6.3591,8.300
4,1317149,I Swear,2025-09-22,"Diagnosed with Tourette Syndrome at 15, John D...",13.8859,8.300
5,92060,Michael Jackson's Thriller,1983-11-21,A night at the movies turns terrifying when Mi...,7.1657,8.252
6,901,City Lights,1931-02-06,A tramp falls in love with a beautiful blind f...,5.7329,8.300
7,637920,Miracle in Cell No. 7,2019-10-10,"Separated from his daughter, a father with an ...",8.9094,8.200
8,15804,A Brighter Summer Day,1991-07-27,"A boy experiences first love, friendships and ...",7.2551,8.252
9,603,The Matrix,1999-03-31,"Set in the 22nd century, The Matrix tells the ...",159.1934,8.247
10,1356039,Counterattack,2025-02-27,When a hostage rescue mission creates a new en...,7.0591,8.243
11,630566,Clouds,2020-10-09,Young musician Zach Sobiech discovers his canc...,4.3407,8.243
12,10376,The Legend of 1900,1998-10-28,Musician Max Tooney goes to sell his prized Co...,5.4582,8.241
13,670,Oldboy,2003-11-21,"With no clue how he came to be imprisoned, dru...",13.8079,8.239
14,299536,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,48.0078,8.236
15,299534,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,29.7660,8.236
16,632632,Given,2020-08-22,Haruki secretly had feelings for Akihiko for y...,3.0338,8.227
17,572154,Rascal Does Not Dream of a Dreaming Girl,2019-06-15,"In Fujisawa, Sakuta Azusagawa is in his second...",3.6130,8.200
18,504253,I Want to Eat Your Pancreas,2018-09-01,After his classmate and crush is diagnosed wit...,5.8545,8.227
19,98,Gladiator,2000-05-04,"After the death of Emperor Marcus Aurelius, hi...",19.1120,8.227

In [19]:
df1.shape

(20, 6)

In [20]:
df1.to_csv('movies.csv')

In [21]:
df1

,id,title,release_date,overview,popularity,vote_average
0,92321,Hotarubi no Mori e,2011-09-17,One hot summer day a little girl gets lost in ...,0.0101,8.255
1,18491,Neon Genesis Evangelion: The End of Evangelion,1997-07-19,"SEELE orders an all-out attack on NERV, aiming...",10.1749,8.300
2,8587,The Lion King,1994-06-15,"Young lion prince Simba, eager to one day beco...",25.9034,8.254
3,975,Paths of Glory,1957-10-25,A commanding officer defends three scapegoats ...,6.3591,8.300
4,1317149,I Swear,2025-09-22,"Diagnosed with Tourette Syndrome at 15, John D...",13.8859,8.300
5,92060,Michael Jackson's Thriller,1983-11-21,A night at the movies turns terrifying when Mi...,7.1657,8.252
6,901,City Lights,1931-02-06,A tramp falls in love with a beautiful blind f...,5.7329,8.300
7,637920,Miracle in Cell No. 7,2019-10-10,"Separated from his daughter, a father with an ...",8.9094,8.200
8,15804,A Brighter Summer Day,1991-07-27,"A boy experiences first love, friendships and ...",7.2551,8.252
9,603,The Matrix,1999-03-31,"Set in the 22nd century, The Matrix tells the ...",159.1934,8.247
10,1356039,Counterattack,2025-02-27,When a hostage rescue mission creates a new en...,7.0591,8.243
11,630566,Clouds,2020-10-09,Young musician Zach Sobiech discovers his canc...,4.3407,8.243
12,10376,The Legend of 1900,1998-10-28,Musician Max Tooney goes to sell his prized Co...,5.4582,8.241
13,670,Oldboy,2003-11-21,"With no clue how he came to be imprisoned, dru...",13.8079,8.239
14,299536,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,48.0078,8.236
15,299534,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,29.7660,8.236
16,632632,Given,2020-08-22,Haruki secretly had feelings for Akihiko for y...,3.0338,8.227
17,572154,Rascal Does Not Dream of a Dreaming Girl,2019-06-15,"In Fujisawa, Sakuta Azusagawa is in his second...",3.6130,8.200
18,504253,I Want to Eat Your Pancreas,2018-09-01,After his classmate and crush is diagnosed wit...,5.8545,8.227
19,98,Gladiator,2000-05-04,"After the death of Emperor Marcus Aurelius, hi...",19.1120,8.227

In [22]:
df.to_csv('movies_page1.csv')

In [23]:
df

,id,title,release_date,overview,popularity,vote_average
0,92321,Hotarubi no Mori e,2011-09-17,One hot summer day a little girl gets lost in ...,0.0101,8.255
1,18491,Neon Genesis Evangelion: The End of Evangelion,1997-07-19,"SEELE orders an all-out attack on NERV, aiming...",10.1749,8.300
2,8587,The Lion King,1994-06-15,"Young lion prince Simba, eager to one day beco...",25.9034,8.254
3,975,Paths of Glory,1957-10-25,A commanding officer defends three scapegoats ...,6.3591,8.300
4,1317149,I Swear,2025-09-22,"Diagnosed with Tourette Syndrome at 15, John D...",13.8859,8.300
5,92060,Michael Jackson's Thriller,1983-11-21,A night at the movies turns terrifying when Mi...,7.1657,8.252
6,901,City Lights,1931-02-06,A tramp falls in love with a beautiful blind f...,5.7329,8.300
7,637920,Miracle in Cell No. 7,2019-10-10,"Separated from his daughter, a father with an ...",8.9094,8.200
8,15804,A Brighter Summer Day,1991-07-27,"A boy experiences first love, friendships and ...",7.2551,8.252
9,603,The Matrix,1999-03-31,"Set in the 22nd century, The Matrix tells the ...",159.1934,8.247
10,1356039,Counterattack,2025-02-27,When a hostage rescue mission creates a new en...,7.0591,8.243
11,630566,Clouds,2020-10-09,Young musician Zach Sobiech discovers his canc...,4.3407,8.243
12,10376,The Legend of 1900,1998-10-28,Musician Max Tooney goes to sell his prized Co...,5.4582,8.241
13,670,Oldboy,2003-11-21,"With no clue how he came to be imprisoned, dru...",13.8079,8.239
14,299536,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,48.0078,8.236
15,299534,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,29.7660,8.236
16,632632,Given,2020-08-22,Haruki secretly had feelings for Akihiko for y...,3.0338,8.227
17,572154,Rascal Does Not Dream of a Dreaming Girl,2019-06-15,"In Fujisawa, Sakuta Azusagawa is in his second...",3.6130,8.200
18,504253,I Want to Eat Your Pancreas,2018-09-01,After his classmate and crush is diagnosed wit...,5.8545,8.227
19,98,Gladiator,2000-05-04,"After the death of Emperor Marcus Aurelius, hi...",19.1120,8.227